package Database;
// Generated Jan 18, 2015 12:02:24 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Datalogg generated by hbm2java
 */
public class Datalogg  implements java.io.Serializable {


     private Date datetime;
     private int channel1;
     private int channel2;
     private int channel3;
     private int channel4;
     private int channel5;
     private int channel6;
     private int channel7;
     private Integer channel8;

    public Datalogg() {
    }

	
    public Datalogg(Date datetime, int channel1, int channel2, int channel3, int channel4, int channel5, int channel6, int channel7) {
        this.datetime = datetime;
        this.channel1 = channel1;
        this.channel2 = channel2;
        this.channel3 = channel3;
        this.channel4 = channel4;
        this.channel5 = channel5;
        this.channel6 = channel6;
        this.channel7 = channel7;
    }
    public Datalogg(Date datetime, int channel1, int channel2, int channel3, int channel4, int channel5, int channel6, int channel7, Integer channel8) {
       this.datetime = datetime;
       this.channel1 = channel1;
       this.channel2 = channel2;
       this.channel3 = channel3;
       this.channel4 = channel4;
       this.channel5 = channel5;
       this.channel6 = channel6;
       this.channel7 = channel7;
       this.channel8 = channel8;
    }
   
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }
    public int getChannel1() {
        return this.channel1;
    }
    
    public void setChannel1(int channel1) {
        this.channel1 = channel1;
    }
    public int getChannel2() {
        return this.channel2;
    }
    
    public void setChannel2(int channel2) {
        this.channel2 = channel2;
    }
    public int getChannel3() {
        return this.channel3;
    }
    
    public void setChannel3(int channel3) {
        this.channel3 = channel3;
    }
    public int getChannel4() {
        return this.channel4;
    }
    
    public void setChannel4(int channel4) {
        this.channel4 = channel4;
    }
    public int getChannel5() {
        return this.channel5;
    }
    
    public void setChannel5(int channel5) {
        this.channel5 = channel5;
    }
    public int getChannel6() {
        return this.channel6;
    }
    
    public void setChannel6(int channel6) {
        this.channel6 = channel6;
    }
    public int getChannel7() {
        return this.channel7;
    }
    
    public void setChannel7(int channel7) {
        this.channel7 = channel7;
    }
    public Integer getChannel8() {
        return this.channel8;
    }
    
    public void setChannel8(Integer channel8) {
        this.channel8 = channel8;
    }




}


